# GoReleaser configuration for QuikGit
# Documentation: https://goreleaser.com

version: 2

project_name: quikgit

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: quikgit
    main: ./cmd/quikgit
    binary: quikgit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md
      - AUTHENTICATION_SETUP.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Documentation'
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: 'Other changes'
      order: 999

# Homebrew
# To enable: Create lvcasx1/homebrew-tap repo and set HOMEBREW_TAP_GITHUB_TOKEN secret
brews:
  - repository:
      owner: lvcasx1
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://github.com/lvcasx1/quikgit
    description: "A GitHub repository manager with terminal user interface (TUI)"
    license: MIT
    skip_upload: true  # Change to 'auto' when repo is ready
    dependencies:
      - name: git
    test: |
      system "#{bin}/quikgit", "--version"
    install: |
      bin.install "quikgit"
    caveats: |
      To get started with QuikGit:

        1. Authenticate with GitHub:
           quikgit

        2. For QR code authentication, set up GitHub OAuth App:
           See: https://github.com/lvcasx1/quikgit/blob/main/AUTHENTICATION_SETUP.md

        3. Alternatively, use a personal access token via environment variable:
           export GITHUB_TOKEN=your_token_here

# Scoop (Windows)
# To enable: Create lvcasx1/scoop-bucket repo and set SCOOP_GITHUB_TOKEN secret
scoops:
  - repository:
      owner: lvcasx1
      name: scoop-bucket
      token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
    directory: bucket
    homepage: https://github.com/lvcasx1/quikgit
    description: A GitHub repository manager with terminal user interface (TUI)
    license: MIT
    skip_upload: true  # Change to 'auto' when repo is ready

# nFPM - DEB and RPM packages
nfpms:
  - id: quikgit
    package_name: quikgit
    vendor: LvcasX1
    homepage: https://github.com/lvcasx1/quikgit
    maintainer: LvcasX1 <noreply@github.com>
    description: |
      A GitHub repository manager with terminal user interface (TUI).
      QuikGit provides an intuitive way to search, clone, and set up repositories
      with automatic dependency installation for multiple languages.
    license: MIT

    formats:
      - deb
      - rpm
      - apk

    bindir: /usr/bin

    dependencies:
      - git

    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/quikgit/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/quikgit/README.md
      - src: ./AUTHENTICATION_SETUP.md
        dst: /usr/share/doc/quikgit/AUTHENTICATION_SETUP.md

    # DEB-specific
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

    # RPM-specific
    rpm:
      group: Applications/Internet
      compression: lzma
      summary: GitHub repository manager TUI

# AUR (Arch Linux)
# To enable: Set up AUR SSH key and set AUR_SSH_PRIVATE_KEY secret
# See: https://wiki.archlinux.org/title/AUR_submission_guidelines
aurs:
  - name: quikgit-bin
    homepage: https://github.com/lvcasx1/quikgit
    description: "A GitHub repository manager with terminal user interface (TUI) (binary release)"
    maintainers:
      - 'LvcasX1 <noreply@github.com>'
    license: MIT
    private_key: "{{ .Env.AUR_SSH_PRIVATE_KEY }}"
    git_url: 'ssh://aur@aur.archlinux.org/quikgit-bin.git'
    skip_upload: true  # Change to 'auto' when AUR SSH key is configured
    depends:
      - git
    package: |-
      # bin
      install -Dm755 "./quikgit" "${pkgdir}/usr/bin/quikgit"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/quikgit/LICENSE"

      # documentation
      install -Dm644 "./README.md" "${pkgdir}/usr/share/doc/quikgit/README.md"
      install -Dm644 "./AUTHENTICATION_SETUP.md" "${pkgdir}/usr/share/doc/quikgit/AUTHENTICATION_SETUP.md"
    commit_author:
      name: LvcasX1
      email: noreply@github.com

# Release settings
release:
  github:
    owner: lvcasx1
    name: quikgit
  name_template: "Release {{.Version}}"
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## QuikGit {{.Version}}

    **Installation Options:**

    ### Package Managers
    ```bash
    # Homebrew (macOS/Linux)
    brew tap lvcasx1/tap
    brew install quikgit

    # Scoop (Windows)
    scoop bucket add lvcasx1 https://github.com/lvcasx1/scoop-bucket
    scoop install quikgit

    # AUR (Arch Linux)
    yay -S quikgit-bin

    # Debian/Ubuntu
    # Download the .deb file below and install with:
    sudo dpkg -i quikgit_{{.Version}}_Linux_x86_64.deb

    # Fedora/RHEL/CentOS
    # Download the .rpm file below and install with:
    sudo rpm -i quikgit_{{.Version}}_Linux_x86_64.rpm
    ```

    ### Direct Download
    Download the appropriate archive for your platform below.

  footer: |
    **Full Changelog**: https://github.com/lvcasx1/quikgit/blob/main/CHANGELOG.md

    ---

    **Getting Started:**
    1. Get your GitHub Personal Access Token from https://github.com/settings/tokens
    2. Run: `quikgit`
    3. Follow the authentication prompts
    4. Start searching and cloning repositories!

    **Supported Languages & Frameworks:**
    Go, Node.js (npm/yarn), Python (pip/pipenv/poetry), Ruby, Rust, Java, C++, C#, Swift, PHP, Dart,
    Next.js, Vue.js, Angular, Svelte, Nuxt, Gatsby, and more!

# Announce releases
announce:
  skip: '{{gt .Patch 0}}'  # Only announce major/minor releases, not patches
